import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SideMenu from "@/components/shared/SideMenu";
import SharedFooter from "@/components/shared/SharedFooter";
import SmoothScroll from "@/components/shared/SmoothScroll";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-black text-white overflow-x-clip`}
      >
        <SideMenu />
        <SmoothScroll>
          {children}
          <SharedFooter />
        </SmoothScroll>
      </body>
    </html>
  );
}
